FROM arm64v8/python:3.12.10-bookworm


ARG AIRFLOW_USER
ENV AIRFLOW_USER ${AIRFLOW_USER}

ARG AIRFLOW_PASSWORD
ENV AIRFLOW_PASSWORD ${AIRFLOW_PASSWORD}

RUN ["pip", "install", "fastapi[standard]", "requests", "cachetools", "python-dotenv", "loki-logger-handler"]

WORKDIR /app

COPY . .

WORKDIR /app/api

ENTRYPOINT ["python3", "run.py"]

EXPOSE 5003
