name: Build and push changes
run-name: Build and push changes from commit ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

jobs:
  build-push-api:
    name: Build and Push Docker Image for API
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iyadelwy/portfolio-api-image:latest
          secret-envs: |
            AIRFLOW_USER=${{ secrets.AIRFLOW_USER }}
            AIRFLOW_PASSWORD=${{ secrets.AIRFLOW_PASSWORD }}

  build-push-vm:
    name: Build and Push Docker Image for VM
    runs-on: ubuntu-latest
    needs: build-push-api
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:vm-container"
          tags: iyadelwy/portfolio-vm-image:latest
