name: Build, push and deploy changes
run-name: Build, push and deploy changes from commit ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

jobs:
  build-push-api:
    name: Build and Push Docker Image for API
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iyadelwy/portfolio-api-image:latest

  build-push-vm:
    name: Build and Push Docker Image for VM
    runs-on: ubuntu-latest
    needs: build-push-api
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:vm-container"
          tags: iyadelwy/portfolio-vm-image:latest

  rollout-restart-deployment:
    name: Restart all deployments in portfolio namespace
    runs-on: ubuntu-latest
    needs: [build-push-api, build-push-vm]
    steps:
      - name: Connect to tailscale network
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Restart deployments
        uses: actions-hub/kubectl@master
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
          KUBE_USERNAME: none
          KUBE_PASSWORD: none
        with:
          args: rollout restart deployment -n portfolio
