name: Build, push and deploy changes
run-name: Build, push and deploy changes from commit ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

jobs:
  # build-push-api:
  #   name: Build and Push Docker Image for API
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         tags: iyadelwy/portfolio-api-image:latest

  # build-push-vm:
  #   name: Build and Push Docker Image for VM
  #   runs-on: ubuntu-latest
  #   needs: build-push-api
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         context: "{{defaultContext}}:vm-container"
  #         tags: iyadelwy/portfolio-vm-image:latest

  rollout-restart-deployment:
    name: Restart all deployments in portfolio namespace
    runs-on: ubuntu-latest
    # needs: [build-push-api, build-push-vm]
    steps:
      - name: Connect to tailscale network
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: kEAgxRCeM711CNTRL
          oauth-secret: tskey-client-kEAgxRCeM711CNTRL-rtCEDLaLxDhuf4HnQ8EDDhB8HMMY6AdWd
          tags: [tag:k8s-operator, tag:k8s-readers]
      - name: Restart deployments
        uses: actions-hub/kubectl@master
        env:
          KUBE_HOST: tailscale-operator-1.tail81b504.ts.net:443
          KUBE_CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyakNDQXpTZ0F3SUJBZ0lTQkJBbi8zNmQzNW4xVkVWZTNzRTIxVnBCTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpOVEFlRncweU5UQXlNVEl4T0RBNU1UVmFGdzB5TlRBMU1UTXhPREE1TVRSYU1ERXhMekF0QmdOVkJBTVRKblJoCmFXeHpZMkZzWlMxdmNHVnlZWFJ2Y2kweExuUmhhV3c0TVdJMU1EUXVkSE11Ym1WME1Ga3dFd1lIS29aSXpqMEMKQVFZSUtvWkl6ajBEQVFjRFFnQUV1NlE3Z2doUVc4WlVDMGhhVXcyQUZRN0h0OEs5TFVLVDBNVElMTDU2UGJaawp0SU9IWDhtUzhyRXZHbjcyeDZCdm0zK2ZZZGZaOWFRRlFCL1pIVloxenFPQ0Fpa3dnZ0lsTUE0R0ExVWREd0VCCi93UUVBd0lIZ0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVEFRSC8KQkFJd0FEQWRCZ05WSFE0RUZnUVVpUUJYWklabnArZUoxb2k4bElyeHJlN0xJRmN3SHdZRFZSMGpCQmd3Rm9BVQpueXRmenp3aFQ1MEV0KzByTE1UR2NJdlMxdzB3VlFZSUt3WUJCUVVIQVFFRVNUQkhNQ0VHQ0NzR0FRVUZCekFCCmhoVm9kSFJ3T2k4dlpUVXVieTVzWlc1amNpNXZjbWN3SWdZSUt3WUJCUVVITUFLR0ZtaDBkSEE2THk5bE5TNXAKTG14bGJtTnlMbTl5Wnk4d01RWURWUjBSQkNvd0tJSW1kR0ZwYkhOallXeGxMVzl3WlhKaGRHOXlMVEV1ZEdGcApiRGd4WWpVd05DNTBjeTV1WlhRd0V3WURWUjBnQkF3d0NqQUlCZ1puZ1F3QkFnRXdnZ0VGQmdvckJnRUVBZFo1CkFnUUNCSUgyQklIekFQRUFkZ0NpNHdya1JlKzlyWnQrT08xSFozZFQxNEpiaEpUWEsxNGJMTVM1VUtSSDV3QUEKQVpUN2oyQ3BBQUFFQXdCSE1FVUNJUUNTTlhxRTA1V0pXN0RDcThmSUVKUHJhVURXU21LZ0YxUGNzVmlRZGJQNgpqQUlnTFJ4MDM3THl4c04wVEJHejA1a0FpbWpWM0R6UVpUUTh0Yk1GdzlwRldmd0Fkd0FUU3Q4YXRaaENDWGdNCmIrOU1lcEdrRnJjalNjNVlWMnJmcnRxbndxdmdJZ0FBQVpUN2oySlJBQUFFQXdCSU1FWUNJUUNOUkRkd0k2alkKalFsZWczUHFKOVBDN2JtMUhCWm9IWlJGZ2lqcjRGUjdXQUloQUtoWFZNL3lmYU94SXJLVEsxTmRJWC85eFc4Uwowa2JOTnlZRG9NMGYrTTRtTUFvR0NDcUdTTTQ5QkFNREEyZ0FNR1VDTVFETFJqNndmdGI4ckVmL0Ntc3JYRXJJCjE3US90S0RvUE9qQUc3bU1ZaEw4bUlRdXhTSVhXcVNTdHEzcWE3aEpXRW9DTUd5dlJLUThkMmFFdTB2SU1iRkcKdW9YcUVyTFYvWXpNc0FoMTBYMlViMFNBYVo0bXNEdTY1MXhMVG85K016eWJVQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVWekNDQWorZ0F3SUJBZ0lSQUlPUGJHUE9zVG1NWWdaaWd4WEovZDR3RFFZSktvWklodmNOQVFFTEJRQXcKVHpFTE1Ba0dBMVVFQmhNQ1ZWTXhLVEFuQmdOVkJBb1RJRWx1ZEdWeWJtVjBJRk5sWTNWeWFYUjVJRkpsYzJWaApjbU5vSUVkeWIzVndNUlV3RXdZRFZRUURFd3hKVTFKSElGSnZiM1FnV0RFd0hoY05NalF3TXpFek1EQXdNREF3CldoY05NamN3TXpFeU1qTTFPVFU1V2pBeU1Rc3dDUVlEVlFRR0V3SlZVekVXTUJRR0ExVUVDaE1OVEdWMEozTWcKUlc1amNubHdkREVMTUFrR0ExVUVBeE1DUlRVd2RqQVFCZ2NxaGtqT1BRSUJCZ1VyZ1FRQUlnTmlBQVFOQ3pxSwphMkdPdHUvY1gxam54a0pGVkt0ajltWmhTQW91V1hXMGdRSTNVTGMvRm5uY21PeWhLSmR5SUJ3c3o5VjhVaUJPClZIaGJoQlJyd0pDdWhlekFVVUU4V29kL0JrM1UvbURSK213dDRYMlZFSWlpQ0ZRUG1ScE01dW9Lck5pamdmZ3cKZ2ZVd0RnWURWUjBQQVFIL0JBUURBZ0dHTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApBVEFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJTZksxL1BQQ0ZQblFTMzdTc3N4TVp3Cmk5TFhEVEFmQmdOVkhTTUVHREFXZ0JSNXRGbm1lN2JsNUFGemdBaUl5QnBZOXVtYmJqQXlCZ2dyQmdFRkJRY0IKQVFRbU1DUXdJZ1lJS3dZQkJRVUhNQUtHRm1oMGRIQTZMeTk0TVM1cExteGxibU55TG05eVp5OHdFd1lEVlIwZwpCQXd3Q2pBSUJnWm5nUXdCQWdFd0p3WURWUjBmQkNBd0hqQWNvQnFnR0lZV2FIUjBjRG92TDNneExtTXViR1Z1ClkzSXViM0puTHpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUgzS2RORVZDUWRxazBMS3l1TkltVEtkUkpZMUMKMnV3MlNKYWp1aHFreUdQWThDK3p6c3VmWittZ25obnExQTJLVlFPU3lrT0VuVWJ4MWN5NjM3ckJBaWh4OTdyKwpiY3diWk02c1RESWFFcmlSL1BMazZMS3M5QmUwdW9WeGdPS0RjcEc5c3ZEMzNKK0c5TGNmdjFLOWx1RG1TVGdHCjZYTkZJTjV2Zkk1Z3MvbE1QeW9qRU1kSXpLOWJsY2wyLzF2S3hPOFdHQ2NqdnNRMW5KL1B3dDhMUVpCZk9GeVYKWFA4dWJBcC9hdTNkYzRFS1dHOU1PNXpjeDFxVDkrTlhSR2RWV3hHdm1CRlJBYWpjaU1mWE1FMVp1R21rMy9HTwprb0FNN1pralptbGV5b2tQMUxHem1mSmNVZDlzN2VldTEvOS9lZzVYbFhkLzU1R3RZakFNK0M0REc1aTdlYU5xCmNtMkYreXhZSVB0NmNiYnRZVk5KQ0dmSFdxSEVRNEZZU3RVeUZudjhzanlxVTh5cGdaYU5KOWFWY1dTSUNMT0kKRTEvUXYvN29Lc25aQ1dKOTI2d1U2UnFHMU9ZUEdPaTF6dUFCaEx3NjFjdVBWRFQyOG5RUy9lNno5NWNKWHEwZQpLMUJjYUo2Zkpac21ialJnRDVwM212RWY1dmRRTTdNQ0V2VTB0SGJzeDJJNW1ISEpvQUJIYjhLVkJnV3AvbGNYCkdXaVdhZU95QjdSUCtPZkR0dmkyT3NhcHhYaVY3dk5WczdmTWxyUmpZMWpvS2FxbW15Y25CdkFxMTRBRWJ0eUwKc1ZmT1M2NkI4YXBrZUZYMk5ZNFhQRVlWNFpTQ2U4VkhQcmRyRVJrMndJTEczVC9FR21TSWtDWVZVTVNuam1KZApWUUQ5RjZOYS8rem1YQ2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          KUBE_USERNAME: none
          KUBE_PASSWORD: none
        with:
          args: rollout restart deployment -n portfolio
